### ISSUE TITLE
Nodes may only utilize a single storage cluster

### ISSUE THREAD

**Issue by brianredbeard** [coreos/quartermaster#89]
Currently while working through an example, I have three node cluster as follows:

```
+----------+ +----------+ +----------+
| node1    | | node2    | | node3    |
|          | |          | |          |
|          | |          | |          |
| RAID5    | | RAID5    | | RAID5    |
|  - 2TB   | |  - 2TB   | |  - 2 TB  |
|          | |          | |          |
| NVMe     | |          | |          |
|  - 120GB | |          | |          |
|          | |          | |          |
|          | |          | |          |
+----------+ +----------+ +----------+
```

In this configuration, I have two distinct classes of storage.  

I then attempted to define two storage clusters, with the RAID 5 volumes of nodes 1, 2, and 3 being a member of one StorageClustr and the NVMe disk of node 1 being a separate storage cluster.

In attempting to define both storage pools as distinct clusters, I run into issues with the use of host paths being utilized, e.g.:

```
    volumeMounts:
    - mountPath: /var/lib/glusterd
      name: glusterfs-config
...
  volumes:
  - hostPath:
      path: /var/lib/glusterfs-container/glusterd
    name: glusterfs-config
```

In this case the use of `glusterfs-config` will always conflict with the definition of any other StorageClusters on the host.

Potentially using the cluster UUID as a part of the URL can make it deterministic from the host perspective, yet still allow for the definition of multiple StorageClusters.
